services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.server
    ports:
      - "80:80"
      - "8000:8000"
    env_file:
      - .env
    develop:
      watch:
        - path: src/service/apis/
          action: sync+restart
          target: /app/apis/

  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - server
    environment:
      - AGENT_URL=http://agent_service
    develop:
      watch:
        - path: src/service/run_streamlit.py
          action: sync+restart
          target: /app/run_streamlit.py