services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.server
    ports:
      - "80:80"
      - "8000:8000"
    env_file:
      - .env
    develop:
      watch:
        - path: src/service/apis/
          action: sync+restart
          target: /app/apis/