[project]
name = "rag-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.10.10",
    "pymupdf>=1.24.11",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
