FROM python:3.12.3-slim

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
ENV UV_COMPILE_BYTECODE=1

COPY pyproject.toml .
COPY uv.lock .
RUN pip install --no-cache-dir uv
RUN uv sync --frozen --no-install-project --no-dev

COPY src/service/agent ./agent/
COPY src/service/apis ./apis/
COPY src/service/schema ./schema/
COPY src/service/run_server.py .

CMD ["python", "run_server.py"]